### ISSUE TITLE
Text input fields: support copy & paste via keyboard shortcuts & menus (Mac OS X)

### ISSUE THREAD

**Issue by jonaswitt** [RafalWilinski/dynobase-roadmap#38]
Reproduce:

* Open Dynobase 0.1.3 on Mac OS X 10.14.6
* Select a DynamoDB table to bring up the "Query" form
* Attempt to enter data into any text input field (e.g. Partition Key field) via copy & paste (a fairly critical use case for me, and I suppose in a development context in general; I don't expect many DynamoDB keys are easy to type out by hand)

Expected Behavior:

* Standard keyboard shortcuts (e.g. Cmd-V) should work
* There should be an "Edit" menu item in the app's menu bar giving access to standard Cut/Copy/Paste functionality
* Ideally there would also be a context (right click) menu in each input field giving access to these capabilities

Actual Behavior:

* Keyboard shortcuts don't work and there are no menus allowing copy & paste at all, forcing the user to type potentially lengthy/cryptic values by hand.

**Comment by RafalWilinski** [comment]
Thanks for reporting an issue, looking into it!

**Comment by RafalWilinski** [comment]
Fixed in 0.1.4! https://github.com/RafalWilinski/dynobase/releases/tag/0.1.4
